#!/usr/bin/env /bin/bash

# @description: Run Astro CLI in the node containerdc

set -ed

DEFAULT_TASK="dev --host"

if [[ -z $@ ]]
then
    echo -e "empty task param, run default ${DEFAULT_TASK} task"
    TASK=$DEFAULT_TASK
else
    TASK=$@
fi

echo -e "running $TASK task"

docker exec -it ${PROJECT_NAME}_node /bin/bash -c "\
umask g=rwx,u=rwx,o=rwx &&\
cd /var/www &&\
npx astro $TASK"

