#!/usr/bin/env /bin/bash

# @description: Create a backup of the database and files

set -e

docker exec -i ${PROJECT_NAME}_db /bin/bash -c "mysqldump -u root -proot default --max_allowed_packet=512M" > "${PROJECT_ROOT}/.docker/backup/db.sql"
rsync -avhP "${PROJECT_ROOT}/public/uploads/" "${PROJECT_ROOT}/.docker/backup/uploads/"

cd "${PROJECT_ROOT}/.docker/backup"

rm -rf backup.tar.gz
tar -czvf backup.tar.gz .

cd -

echo -e "📦 Backup successfully created"
