#!/usr/bin/env /bin/bash

# @description: Restore database and files from backup

set -e

echo -e "Importing database..."
docker exec -i ${PROJECT_NAME}_db mysql -u root -proot default < ${PROJECT_ROOT}/.docker/backup/db.sql

echo -e "✅ Database restored"


